name: 🎮 Arcade Contribution Games

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: 🎮 Generate Arcade Games
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: bikram73
          github_token: ${{ secrets.GITHUB_TOKEN }}
          games: "pacman,breakout,galaga,puzzle-bobble"

      - name: 🚀 Publish SVGs
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
