name: 👽 Commit Invaders

on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate Commit Invaders
        uses: Goblinlordx/commit-invaders@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_user_name: bikram73
          output_branch: output-commit-invaders
          output_file: commit-invaders.svg
          no_scoreboard: false
